# Used to configure redis
# The redis config reads this file directly and looks at the RAILS_ENV servers from lib/configure_resque.rb

defaults: &defaults
  server: localhost
  options:
    namespace: jupiter

development:
  <<: *defaults

test:
  <<: *defaults

production: &production
  <<: *defaults
  server: redis.east.pipelinedeals.com
